#!/bin/bash

linux32 bash
export CPPFLAGS=-UPHNALG
export CFLAGS="-m32 -ansi -D_SVID_SOURCE -DOSS_AUDIO -D'ARCH=\"$host_cpu\"' $CFLAGS"
cd htk
./configure --prefix=$HOME/htk --disable-hslab --disable-hlmtools 

make clean
make all
make install

export PATH="$PWD/htk:$PWD/htk/bin:$PATH"

#cd ../sox-14.4.2
#./configure --prefix=$HOME

#make 
#make install

#export PATH="$PWD/sox-14.4.2:$PATH"
