#!/bin/bash

dpkg --add-architecture i386
#linux32 bash
export CPPFLAGS=-UPHNALG
cd htk
./configure --prefix=$HOME/htk --disable-hslab --disable-hlmtools --build=x86_64-linux-gnu

make clean
make all
make install

export PATH="$PWD/htk:$PWD/htk/bin:$PATH"

#cd ../sox-14.4.2
#./configure --prefix=$HOME

#make 
#make install

#export PATH="$PWD/sox-14.4.2:$PATH"
