#!/bin/bash

linux32 bash
cd htk
#export CPPFLAGS=-UPHNALG
#export CFLAGS="-m32 -ansi -D_SVID_SOURCE -DOSS_AUDIO -D'ARCH=\"$host_cpu\"' $CFLAGS"
#make clean
export CPPFLAGS=-UPHNALG
#echo $host_cpu
#export CFLAGS="-m32 -ansi -D_SVID_SOURCE -DOSS_AUDIO -D'ARCH=\"$host_cpu\"' $CFLAGS"
#./configure CC=gcc-3.4 --prefix=$HOME/htk --disable-hslab --disable-hlmtools
./configure --prefix=$HOME/htk --disable-hslab --disable-hlmtools

make all
make install
